/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PlanYourTripRouteImport } from './routes/plan-your-trip'
import { Route as PlanTripRouteImport } from './routes/plan-trip'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MapRouteImport } from './routes/map'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AttractionsRouteImport } from './routes/attractions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as PlanYourTripGuideRouteImport } from './routes/plan-your-trip.guide'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as ItinerariesSlugRouteImport } from './routes/itineraries.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as GuidesIdRouteImport } from './routes/guides.$id'
import { Route as GalleryIdRouteImport } from './routes/gallery.$id'
import { Route as EventsStatusRouteImport } from './routes/events.status'
import { Route as BookStatusRouteImport } from './routes/book.status'
import { Route as AttractionsSlugRouteImport } from './routes/attractions.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminPartnersRouteImport } from './routes/admin/partners'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminItinerariesRouteImport } from './routes/admin/itineraries'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminHeroRouteImport } from './routes/admin/hero'
import { Route as AdminGuidesRouteImport } from './routes/admin/guides'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminEventRegistrationsRouteImport } from './routes/admin/event-registrations'
import { Route as AdminContactRouteImport } from './routes/admin/contact'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAttractionsRouteImport } from './routes/admin/attractions'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as AdminPartnersIndexRouteImport } from './routes/admin/partners.index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin/pages.index'
import { Route as AdminItinerariesIndexRouteImport } from './routes/admin/itineraries.index'
import { Route as AdminInquiriesIndexRouteImport } from './routes/admin/inquiries.index'
import { Route as AdminGuidesIndexRouteImport } from './routes/admin/guides.index'
import { Route as AdminGalleryIndexRouteImport } from './routes/admin/gallery.index'
import { Route as AdminEventRegistrationsIndexRouteImport } from './routes/admin/event-registrations.index'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin/bookings.index'
import { Route as AdminAttractionsIndexRouteImport } from './routes/admin/attractions.index'
import { Route as EventsTicketTokenRouteImport } from './routes/events.ticket.$token'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminPartnersIdRouteImport } from './routes/admin/partners.$id'
import { Route as AdminPagesPageKeyRouteImport } from './routes/admin/pages.$pageKey'
import { Route as AdminItinerariesIdRouteImport } from './routes/admin/itineraries.$id'
import { Route as AdminInquiriesIdRouteImport } from './routes/admin/inquiries.$id'
import { Route as AdminGuidesIdRouteImport } from './routes/admin/guides.$id'
import { Route as AdminGalleryAlbumIdRouteImport } from './routes/admin/gallery.$albumId'
import { Route as AdminEventRegistrationsRefRouteImport } from './routes/admin/event-registrations.$ref'
import { Route as AdminBookingsRefRouteImport } from './routes/admin/bookings.$ref'
import { Route as AdminAttractionsIdRouteImport } from './routes/admin/attractions.$id'
import { Route as AdminAnnouncementsIdRouteImport } from './routes/admin/announcements.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanYourTripRoute = PlanYourTripRouteImport.update({
  id: '/plan-your-trip',
  path: '/plan-your-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanTripRoute = PlanTripRouteImport.update({
  id: '/plan-trip',
  path: '/plan-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AttractionsRoute = AttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanYourTripGuideRoute = PlanYourTripGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => PlanYourTripRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const ItinerariesSlugRoute = ItinerariesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ItinerariesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesIdRoute = GuidesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GuidesRoute,
} as any)
const GalleryIdRoute = GalleryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GalleryRoute,
} as any)
const EventsStatusRoute = EventsStatusRouteImport.update({
  id: '/events/status',
  path: '/events/status',
  getParentRoute: () => rootRouteImport,
} as any)
const BookStatusRoute = BookStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => BookRoute,
} as any)
const AttractionsSlugRoute = AttractionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AttractionsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminItinerariesRoute = AdminItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGuidesRoute = AdminGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEventRegistrationsRoute = AdminEventRegistrationsRouteImport.update({
  id: '/event-registrations',
  path: '/event-registrations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAttractionsRoute = AdminAttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersIndexRoute = AdminPartnersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPartnersRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminItinerariesIndexRoute = AdminItinerariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminItinerariesRoute,
} as any)
const AdminInquiriesIndexRoute = AdminInquiriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminInquiriesRoute,
} as any)
const AdminGuidesIndexRoute = AdminGuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGuidesRoute,
} as any)
const AdminGalleryIndexRoute = AdminGalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGalleryRoute,
} as any)
const AdminEventRegistrationsIndexRoute =
  AdminEventRegistrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminEventRegistrationsRoute,
  } as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBookingsRoute,
} as any)
const AdminAttractionsIndexRoute = AdminAttractionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAttractionsRoute,
} as any)
const EventsTicketTokenRoute = EventsTicketTokenRouteImport.update({
  id: '/events/ticket/$token',
  path: '/events/ticket/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersIdRoute = AdminPartnersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPartnersRoute,
} as any)
const AdminPagesPageKeyRoute = AdminPagesPageKeyRouteImport.update({
  id: '/$pageKey',
  path: '/$pageKey',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminItinerariesIdRoute = AdminItinerariesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminItinerariesRoute,
} as any)
const AdminInquiriesIdRoute = AdminInquiriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInquiriesRoute,
} as any)
const AdminGuidesIdRoute = AdminGuidesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminGuidesRoute,
} as any)
const AdminGalleryAlbumIdRoute = AdminGalleryAlbumIdRouteImport.update({
  id: '/$albumId',
  path: '/$albumId',
  getParentRoute: () => AdminGalleryRoute,
} as any)
const AdminEventRegistrationsRefRoute =
  AdminEventRegistrationsRefRouteImport.update({
    id: '/$ref',
    path: '/$ref',
    getParentRoute: () => AdminEventRegistrationsRoute,
  } as any)
const AdminBookingsRefRoute = AdminBookingsRefRouteImport.update({
  id: '/$ref',
  path: '/$ref',
  getParentRoute: () => AdminBookingsRoute,
} as any)
const AdminAttractionsIdRoute = AdminAttractionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAttractionsRoute,
} as any)
const AdminAnnouncementsIdRoute = AdminAnnouncementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAnnouncementsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/attractions': typeof AttractionsRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/contact': typeof ContactRoute
  '/culture': typeof CultureRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/health': typeof HealthRoute
  '/itineraries': typeof ItinerariesRouteWithChildren
  '/map': typeof MapRoute
  '/news': typeof NewsRouteWithChildren
  '/plan-trip': typeof PlanTripRoute
  '/plan-your-trip': typeof PlanYourTripRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRouteWithChildren
  '/admin/attractions': typeof AdminAttractionsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/contact': typeof AdminContactRoute
  '/admin/event-registrations': typeof AdminEventRegistrationsRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/gallery': typeof AdminGalleryRouteWithChildren
  '/admin/guides': typeof AdminGuidesRouteWithChildren
  '/admin/hero': typeof AdminHeroRoute
  '/admin/inquiries': typeof AdminInquiriesRouteWithChildren
  '/admin/itineraries': typeof AdminItinerariesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/partners': typeof AdminPartnersRouteWithChildren
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/attractions/$slug': typeof AttractionsSlugRoute
  '/book/status': typeof BookStatusRoute
  '/events/status': typeof EventsStatusRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/guides/$id': typeof GuidesIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/plan-your-trip/guide': typeof PlanYourTripGuideRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/announcements/$id': typeof AdminAnnouncementsIdRoute
  '/admin/attractions/$id': typeof AdminAttractionsIdRoute
  '/admin/bookings/$ref': typeof AdminBookingsRefRoute
  '/admin/event-registrations/$ref': typeof AdminEventRegistrationsRefRoute
  '/admin/gallery/$albumId': typeof AdminGalleryAlbumIdRoute
  '/admin/guides/$id': typeof AdminGuidesIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/itineraries/$id': typeof AdminItinerariesIdRoute
  '/admin/pages/$pageKey': typeof AdminPagesPageKeyRoute
  '/admin/partners/$id': typeof AdminPartnersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/events/ticket/$token': typeof EventsTicketTokenRoute
  '/admin/attractions/': typeof AdminAttractionsIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/event-registrations/': typeof AdminEventRegistrationsIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/guides/': typeof AdminGuidesIndexRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/itineraries/': typeof AdminItinerariesIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/partners/': typeof AdminPartnersIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attractions': typeof AttractionsRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/contact': typeof ContactRoute
  '/culture': typeof CultureRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/health': typeof HealthRoute
  '/itineraries': typeof ItinerariesRouteWithChildren
  '/map': typeof MapRoute
  '/news': typeof NewsRouteWithChildren
  '/plan-trip': typeof PlanTripRoute
  '/plan-your-trip': typeof PlanYourTripRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/attractions/$slug': typeof AttractionsSlugRoute
  '/book/status': typeof BookStatusRoute
  '/events/status': typeof EventsStatusRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/guides/$id': typeof GuidesIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/plan-your-trip/guide': typeof PlanYourTripGuideRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin': typeof AdminIndexRoute
  '/admin/announcements/$id': typeof AdminAnnouncementsIdRoute
  '/admin/attractions/$id': typeof AdminAttractionsIdRoute
  '/admin/bookings/$ref': typeof AdminBookingsRefRoute
  '/admin/event-registrations/$ref': typeof AdminEventRegistrationsRefRoute
  '/admin/gallery/$albumId': typeof AdminGalleryAlbumIdRoute
  '/admin/guides/$id': typeof AdminGuidesIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/itineraries/$id': typeof AdminItinerariesIdRoute
  '/admin/pages/$pageKey': typeof AdminPagesPageKeyRoute
  '/admin/partners/$id': typeof AdminPartnersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/events/ticket/$token': typeof EventsTicketTokenRoute
  '/admin/attractions': typeof AdminAttractionsIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/event-registrations': typeof AdminEventRegistrationsIndexRoute
  '/admin/gallery': typeof AdminGalleryIndexRoute
  '/admin/guides': typeof AdminGuidesIndexRoute
  '/admin/inquiries': typeof AdminInquiriesIndexRoute
  '/admin/itineraries': typeof AdminItinerariesIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/partners': typeof AdminPartnersIndexRoute
  '/api/v1': typeof ApiV1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/attractions': typeof AttractionsRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/contact': typeof ContactRoute
  '/culture': typeof CultureRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/health': typeof HealthRoute
  '/itineraries': typeof ItinerariesRouteWithChildren
  '/map': typeof MapRoute
  '/news': typeof NewsRouteWithChildren
  '/plan-trip': typeof PlanTripRoute
  '/plan-your-trip': typeof PlanYourTripRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRouteWithChildren
  '/admin/attractions': typeof AdminAttractionsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/contact': typeof AdminContactRoute
  '/admin/event-registrations': typeof AdminEventRegistrationsRouteWithChildren
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/gallery': typeof AdminGalleryRouteWithChildren
  '/admin/guides': typeof AdminGuidesRouteWithChildren
  '/admin/hero': typeof AdminHeroRoute
  '/admin/inquiries': typeof AdminInquiriesRouteWithChildren
  '/admin/itineraries': typeof AdminItinerariesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/partners': typeof AdminPartnersRouteWithChildren
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/attractions/$slug': typeof AttractionsSlugRoute
  '/book/status': typeof BookStatusRoute
  '/events/status': typeof EventsStatusRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/guides/$id': typeof GuidesIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/itineraries/$slug': typeof ItinerariesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/plan-your-trip/guide': typeof PlanYourTripGuideRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/announcements/$id': typeof AdminAnnouncementsIdRoute
  '/admin/attractions/$id': typeof AdminAttractionsIdRoute
  '/admin/bookings/$ref': typeof AdminBookingsRefRoute
  '/admin/event-registrations/$ref': typeof AdminEventRegistrationsRefRoute
  '/admin/gallery/$albumId': typeof AdminGalleryAlbumIdRoute
  '/admin/guides/$id': typeof AdminGuidesIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/itineraries/$id': typeof AdminItinerariesIdRoute
  '/admin/pages/$pageKey': typeof AdminPagesPageKeyRoute
  '/admin/partners/$id': typeof AdminPartnersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/events/ticket/$token': typeof EventsTicketTokenRoute
  '/admin/attractions/': typeof AdminAttractionsIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/event-registrations/': typeof AdminEventRegistrationsIndexRoute
  '/admin/gallery/': typeof AdminGalleryIndexRoute
  '/admin/guides/': typeof AdminGuidesIndexRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/itineraries/': typeof AdminItinerariesIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/partners/': typeof AdminPartnersIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/attractions'
    | '/book'
    | '/contact'
    | '/culture'
    | '/gallery'
    | '/guides'
    | '/health'
    | '/itineraries'
    | '/map'
    | '/news'
    | '/plan-trip'
    | '/plan-your-trip'
    | '/robots.txt'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/attractions'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/contact'
    | '/admin/event-registrations'
    | '/admin/forgot-password'
    | '/admin/gallery'
    | '/admin/guides'
    | '/admin/hero'
    | '/admin/inquiries'
    | '/admin/itineraries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/users'
    | '/attractions/$slug'
    | '/book/status'
    | '/events/status'
    | '/gallery/$id'
    | '/guides/$id'
    | '/guides/$slug'
    | '/itineraries/$slug'
    | '/news/$id'
    | '/news/$slug'
    | '/plan-your-trip/guide'
    | '/uploads/$'
    | '/admin/'
    | '/admin/announcements/$id'
    | '/admin/attractions/$id'
    | '/admin/bookings/$ref'
    | '/admin/event-registrations/$ref'
    | '/admin/gallery/$albumId'
    | '/admin/guides/$id'
    | '/admin/inquiries/$id'
    | '/admin/itineraries/$id'
    | '/admin/pages/$pageKey'
    | '/admin/partners/$id'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/events/ticket/$token'
    | '/admin/attractions/'
    | '/admin/bookings/'
    | '/admin/event-registrations/'
    | '/admin/gallery/'
    | '/admin/guides/'
    | '/admin/inquiries/'
    | '/admin/itineraries/'
    | '/admin/pages/'
    | '/admin/partners/'
    | '/api/v1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/attractions'
    | '/book'
    | '/contact'
    | '/culture'
    | '/gallery'
    | '/guides'
    | '/health'
    | '/itineraries'
    | '/map'
    | '/news'
    | '/plan-trip'
    | '/plan-your-trip'
    | '/robots.txt'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/contact'
    | '/admin/forgot-password'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/media'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/users'
    | '/attractions/$slug'
    | '/book/status'
    | '/events/status'
    | '/gallery/$id'
    | '/guides/$id'
    | '/guides/$slug'
    | '/itineraries/$slug'
    | '/news/$id'
    | '/news/$slug'
    | '/plan-your-trip/guide'
    | '/uploads/$'
    | '/admin'
    | '/admin/announcements/$id'
    | '/admin/attractions/$id'
    | '/admin/bookings/$ref'
    | '/admin/event-registrations/$ref'
    | '/admin/gallery/$albumId'
    | '/admin/guides/$id'
    | '/admin/inquiries/$id'
    | '/admin/itineraries/$id'
    | '/admin/pages/$pageKey'
    | '/admin/partners/$id'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/events/ticket/$token'
    | '/admin/attractions'
    | '/admin/bookings'
    | '/admin/event-registrations'
    | '/admin/gallery'
    | '/admin/guides'
    | '/admin/inquiries'
    | '/admin/itineraries'
    | '/admin/pages'
    | '/admin/partners'
    | '/api/v1'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/attractions'
    | '/book'
    | '/contact'
    | '/culture'
    | '/gallery'
    | '/guides'
    | '/health'
    | '/itineraries'
    | '/map'
    | '/news'
    | '/plan-trip'
    | '/plan-your-trip'
    | '/robots.txt'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/attractions'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/contact'
    | '/admin/event-registrations'
    | '/admin/forgot-password'
    | '/admin/gallery'
    | '/admin/guides'
    | '/admin/hero'
    | '/admin/inquiries'
    | '/admin/itineraries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/users'
    | '/attractions/$slug'
    | '/book/status'
    | '/events/status'
    | '/gallery/$id'
    | '/guides/$id'
    | '/guides/$slug'
    | '/itineraries/$slug'
    | '/news/$id'
    | '/news/$slug'
    | '/plan-your-trip/guide'
    | '/uploads/$'
    | '/admin/'
    | '/admin/announcements/$id'
    | '/admin/attractions/$id'
    | '/admin/bookings/$ref'
    | '/admin/event-registrations/$ref'
    | '/admin/gallery/$albumId'
    | '/admin/guides/$id'
    | '/admin/inquiries/$id'
    | '/admin/itineraries/$id'
    | '/admin/pages/$pageKey'
    | '/admin/partners/$id'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/events/ticket/$token'
    | '/admin/attractions/'
    | '/admin/bookings/'
    | '/admin/event-registrations/'
    | '/admin/gallery/'
    | '/admin/guides/'
    | '/admin/inquiries/'
    | '/admin/itineraries/'
    | '/admin/pages/'
    | '/admin/partners/'
    | '/api/v1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AttractionsRoute: typeof AttractionsRouteWithChildren
  BookRoute: typeof BookRouteWithChildren
  ContactRoute: typeof ContactRoute
  CultureRoute: typeof CultureRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  GuidesRoute: typeof GuidesRouteWithChildren
  HealthRoute: typeof HealthRoute
  ItinerariesRoute: typeof ItinerariesRouteWithChildren
  MapRoute: typeof MapRoute
  NewsRoute: typeof NewsRouteWithChildren
  PlanTripRoute: typeof PlanTripRoute
  PlanYourTripRoute: typeof PlanYourTripRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EventsStatusRoute: typeof EventsStatusRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  EventsTicketTokenRoute: typeof EventsTicketTokenRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-your-trip': {
      id: '/plan-your-trip'
      path: '/plan-your-trip'
      fullPath: '/plan-your-trip'
      preLoaderRoute: typeof PlanYourTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-trip': {
      id: '/plan-trip'
      path: '/plan-trip'
      fullPath: '/plan-trip'
      preLoaderRoute: typeof PlanTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attractions': {
      id: '/attractions'
      path: '/attractions'
      fullPath: '/attractions'
      preLoaderRoute: typeof AttractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-your-trip/guide': {
      id: '/plan-your-trip/guide'
      path: '/guide'
      fullPath: '/plan-your-trip/guide'
      preLoaderRoute: typeof PlanYourTripGuideRouteImport
      parentRoute: typeof PlanYourTripRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/itineraries/$slug': {
      id: '/itineraries/$slug'
      path: '/$slug'
      fullPath: '/itineraries/$slug'
      preLoaderRoute: typeof ItinerariesSlugRouteImport
      parentRoute: typeof ItinerariesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$id': {
      id: '/guides/$id'
      path: '/$id'
      fullPath: '/guides/$id'
      preLoaderRoute: typeof GuidesIdRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/gallery/$id': {
      id: '/gallery/$id'
      path: '/$id'
      fullPath: '/gallery/$id'
      preLoaderRoute: typeof GalleryIdRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/events/status': {
      id: '/events/status'
      path: '/events/status'
      fullPath: '/events/status'
      preLoaderRoute: typeof EventsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/status': {
      id: '/book/status'
      path: '/status'
      fullPath: '/book/status'
      preLoaderRoute: typeof BookStatusRouteImport
      parentRoute: typeof BookRoute
    }
    '/attractions/$slug': {
      id: '/attractions/$slug'
      path: '/$slug'
      fullPath: '/attractions/$slug'
      preLoaderRoute: typeof AttractionsSlugRouteImport
      parentRoute: typeof AttractionsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/itineraries': {
      id: '/admin/itineraries'
      path: '/itineraries'
      fullPath: '/admin/itineraries'
      preLoaderRoute: typeof AdminItinerariesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/guides': {
      id: '/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AdminGuidesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/event-registrations': {
      id: '/admin/event-registrations'
      path: '/event-registrations'
      fullPath: '/admin/event-registrations'
      preLoaderRoute: typeof AdminEventRegistrationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/attractions': {
      id: '/admin/attractions'
      path: '/attractions'
      fullPath: '/admin/attractions'
      preLoaderRoute: typeof AdminAttractionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners/': {
      id: '/admin/partners/'
      path: '/'
      fullPath: '/admin/partners/'
      preLoaderRoute: typeof AdminPartnersIndexRouteImport
      parentRoute: typeof AdminPartnersRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/itineraries/': {
      id: '/admin/itineraries/'
      path: '/'
      fullPath: '/admin/itineraries/'
      preLoaderRoute: typeof AdminItinerariesIndexRouteImport
      parentRoute: typeof AdminItinerariesRoute
    }
    '/admin/inquiries/': {
      id: '/admin/inquiries/'
      path: '/'
      fullPath: '/admin/inquiries/'
      preLoaderRoute: typeof AdminInquiriesIndexRouteImport
      parentRoute: typeof AdminInquiriesRoute
    }
    '/admin/guides/': {
      id: '/admin/guides/'
      path: '/'
      fullPath: '/admin/guides/'
      preLoaderRoute: typeof AdminGuidesIndexRouteImport
      parentRoute: typeof AdminGuidesRoute
    }
    '/admin/gallery/': {
      id: '/admin/gallery/'
      path: '/'
      fullPath: '/admin/gallery/'
      preLoaderRoute: typeof AdminGalleryIndexRouteImport
      parentRoute: typeof AdminGalleryRoute
    }
    '/admin/event-registrations/': {
      id: '/admin/event-registrations/'
      path: '/'
      fullPath: '/admin/event-registrations/'
      preLoaderRoute: typeof AdminEventRegistrationsIndexRouteImport
      parentRoute: typeof AdminEventRegistrationsRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
    '/admin/attractions/': {
      id: '/admin/attractions/'
      path: '/'
      fullPath: '/admin/attractions/'
      preLoaderRoute: typeof AdminAttractionsIndexRouteImport
      parentRoute: typeof AdminAttractionsRoute
    }
    '/events/ticket/$token': {
      id: '/events/ticket/$token'
      path: '/events/ticket/$token'
      fullPath: '/events/ticket/$token'
      preLoaderRoute: typeof EventsTicketTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners/$id': {
      id: '/admin/partners/$id'
      path: '/$id'
      fullPath: '/admin/partners/$id'
      preLoaderRoute: typeof AdminPartnersIdRouteImport
      parentRoute: typeof AdminPartnersRoute
    }
    '/admin/pages/$pageKey': {
      id: '/admin/pages/$pageKey'
      path: '/$pageKey'
      fullPath: '/admin/pages/$pageKey'
      preLoaderRoute: typeof AdminPagesPageKeyRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/itineraries/$id': {
      id: '/admin/itineraries/$id'
      path: '/$id'
      fullPath: '/admin/itineraries/$id'
      preLoaderRoute: typeof AdminItinerariesIdRouteImport
      parentRoute: typeof AdminItinerariesRoute
    }
    '/admin/inquiries/$id': {
      id: '/admin/inquiries/$id'
      path: '/$id'
      fullPath: '/admin/inquiries/$id'
      preLoaderRoute: typeof AdminInquiriesIdRouteImport
      parentRoute: typeof AdminInquiriesRoute
    }
    '/admin/guides/$id': {
      id: '/admin/guides/$id'
      path: '/$id'
      fullPath: '/admin/guides/$id'
      preLoaderRoute: typeof AdminGuidesIdRouteImport
      parentRoute: typeof AdminGuidesRoute
    }
    '/admin/gallery/$albumId': {
      id: '/admin/gallery/$albumId'
      path: '/$albumId'
      fullPath: '/admin/gallery/$albumId'
      preLoaderRoute: typeof AdminGalleryAlbumIdRouteImport
      parentRoute: typeof AdminGalleryRoute
    }
    '/admin/event-registrations/$ref': {
      id: '/admin/event-registrations/$ref'
      path: '/$ref'
      fullPath: '/admin/event-registrations/$ref'
      preLoaderRoute: typeof AdminEventRegistrationsRefRouteImport
      parentRoute: typeof AdminEventRegistrationsRoute
    }
    '/admin/bookings/$ref': {
      id: '/admin/bookings/$ref'
      path: '/$ref'
      fullPath: '/admin/bookings/$ref'
      preLoaderRoute: typeof AdminBookingsRefRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
    '/admin/attractions/$id': {
      id: '/admin/attractions/$id'
      path: '/$id'
      fullPath: '/admin/attractions/$id'
      preLoaderRoute: typeof AdminAttractionsIdRouteImport
      parentRoute: typeof AdminAttractionsRoute
    }
    '/admin/announcements/$id': {
      id: '/admin/announcements/$id'
      path: '/$id'
      fullPath: '/admin/announcements/$id'
      preLoaderRoute: typeof AdminAnnouncementsIdRouteImport
      parentRoute: typeof AdminAnnouncementsRoute
    }
  }
}

interface AdminAnnouncementsRouteChildren {
  AdminAnnouncementsIdRoute: typeof AdminAnnouncementsIdRoute
}

const AdminAnnouncementsRouteChildren: AdminAnnouncementsRouteChildren = {
  AdminAnnouncementsIdRoute: AdminAnnouncementsIdRoute,
}

const AdminAnnouncementsRouteWithChildren =
  AdminAnnouncementsRoute._addFileChildren(AdminAnnouncementsRouteChildren)

interface AdminAttractionsRouteChildren {
  AdminAttractionsIdRoute: typeof AdminAttractionsIdRoute
  AdminAttractionsIndexRoute: typeof AdminAttractionsIndexRoute
}

const AdminAttractionsRouteChildren: AdminAttractionsRouteChildren = {
  AdminAttractionsIdRoute: AdminAttractionsIdRoute,
  AdminAttractionsIndexRoute: AdminAttractionsIndexRoute,
}

const AdminAttractionsRouteWithChildren =
  AdminAttractionsRoute._addFileChildren(AdminAttractionsRouteChildren)

interface AdminBookingsRouteChildren {
  AdminBookingsRefRoute: typeof AdminBookingsRefRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
}

const AdminBookingsRouteChildren: AdminBookingsRouteChildren = {
  AdminBookingsRefRoute: AdminBookingsRefRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
}

const AdminBookingsRouteWithChildren = AdminBookingsRoute._addFileChildren(
  AdminBookingsRouteChildren,
)

interface AdminEventRegistrationsRouteChildren {
  AdminEventRegistrationsRefRoute: typeof AdminEventRegistrationsRefRoute
  AdminEventRegistrationsIndexRoute: typeof AdminEventRegistrationsIndexRoute
}

const AdminEventRegistrationsRouteChildren: AdminEventRegistrationsRouteChildren =
  {
    AdminEventRegistrationsRefRoute: AdminEventRegistrationsRefRoute,
    AdminEventRegistrationsIndexRoute: AdminEventRegistrationsIndexRoute,
  }

const AdminEventRegistrationsRouteWithChildren =
  AdminEventRegistrationsRoute._addFileChildren(
    AdminEventRegistrationsRouteChildren,
  )

interface AdminGalleryRouteChildren {
  AdminGalleryAlbumIdRoute: typeof AdminGalleryAlbumIdRoute
  AdminGalleryIndexRoute: typeof AdminGalleryIndexRoute
}

const AdminGalleryRouteChildren: AdminGalleryRouteChildren = {
  AdminGalleryAlbumIdRoute: AdminGalleryAlbumIdRoute,
  AdminGalleryIndexRoute: AdminGalleryIndexRoute,
}

const AdminGalleryRouteWithChildren = AdminGalleryRoute._addFileChildren(
  AdminGalleryRouteChildren,
)

interface AdminGuidesRouteChildren {
  AdminGuidesIdRoute: typeof AdminGuidesIdRoute
  AdminGuidesIndexRoute: typeof AdminGuidesIndexRoute
}

const AdminGuidesRouteChildren: AdminGuidesRouteChildren = {
  AdminGuidesIdRoute: AdminGuidesIdRoute,
  AdminGuidesIndexRoute: AdminGuidesIndexRoute,
}

const AdminGuidesRouteWithChildren = AdminGuidesRoute._addFileChildren(
  AdminGuidesRouteChildren,
)

interface AdminInquiriesRouteChildren {
  AdminInquiriesIdRoute: typeof AdminInquiriesIdRoute
  AdminInquiriesIndexRoute: typeof AdminInquiriesIndexRoute
}

const AdminInquiriesRouteChildren: AdminInquiriesRouteChildren = {
  AdminInquiriesIdRoute: AdminInquiriesIdRoute,
  AdminInquiriesIndexRoute: AdminInquiriesIndexRoute,
}

const AdminInquiriesRouteWithChildren = AdminInquiriesRoute._addFileChildren(
  AdminInquiriesRouteChildren,
)

interface AdminItinerariesRouteChildren {
  AdminItinerariesIdRoute: typeof AdminItinerariesIdRoute
  AdminItinerariesIndexRoute: typeof AdminItinerariesIndexRoute
}

const AdminItinerariesRouteChildren: AdminItinerariesRouteChildren = {
  AdminItinerariesIdRoute: AdminItinerariesIdRoute,
  AdminItinerariesIndexRoute: AdminItinerariesIndexRoute,
}

const AdminItinerariesRouteWithChildren =
  AdminItinerariesRoute._addFileChildren(AdminItinerariesRouteChildren)

interface AdminPagesRouteChildren {
  AdminPagesPageKeyRoute: typeof AdminPagesPageKeyRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesPageKeyRoute: AdminPagesPageKeyRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminPartnersRouteChildren {
  AdminPartnersIdRoute: typeof AdminPartnersIdRoute
  AdminPartnersIndexRoute: typeof AdminPartnersIndexRoute
}

const AdminPartnersRouteChildren: AdminPartnersRouteChildren = {
  AdminPartnersIdRoute: AdminPartnersIdRoute,
  AdminPartnersIndexRoute: AdminPartnersIndexRoute,
}

const AdminPartnersRouteWithChildren = AdminPartnersRoute._addFileChildren(
  AdminPartnersRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRouteWithChildren
  AdminAttractionsRoute: typeof AdminAttractionsRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBookingsRoute: typeof AdminBookingsRouteWithChildren
  AdminContactRoute: typeof AdminContactRoute
  AdminEventRegistrationsRoute: typeof AdminEventRegistrationsRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminGalleryRoute: typeof AdminGalleryRouteWithChildren
  AdminGuidesRoute: typeof AdminGuidesRouteWithChildren
  AdminHeroRoute: typeof AdminHeroRoute
  AdminInquiriesRoute: typeof AdminInquiriesRouteWithChildren
  AdminItinerariesRoute: typeof AdminItinerariesRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminPartnersRoute: typeof AdminPartnersRouteWithChildren
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRouteWithChildren,
  AdminAttractionsRoute: AdminAttractionsRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminBookingsRoute: AdminBookingsRouteWithChildren,
  AdminContactRoute: AdminContactRoute,
  AdminEventRegistrationsRoute: AdminEventRegistrationsRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminGalleryRoute: AdminGalleryRouteWithChildren,
  AdminGuidesRoute: AdminGuidesRouteWithChildren,
  AdminHeroRoute: AdminHeroRoute,
  AdminInquiriesRoute: AdminInquiriesRouteWithChildren,
  AdminItinerariesRoute: AdminItinerariesRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminPartnersRoute: AdminPartnersRouteWithChildren,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AttractionsRouteChildren {
  AttractionsSlugRoute: typeof AttractionsSlugRoute
}

const AttractionsRouteChildren: AttractionsRouteChildren = {
  AttractionsSlugRoute: AttractionsSlugRoute,
}

const AttractionsRouteWithChildren = AttractionsRoute._addFileChildren(
  AttractionsRouteChildren,
)

interface BookRouteChildren {
  BookStatusRoute: typeof BookStatusRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookStatusRoute: BookStatusRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface GalleryRouteChildren {
  GalleryIdRoute: typeof GalleryIdRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryIdRoute: GalleryIdRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface GuidesRouteChildren {
  GuidesIdRoute: typeof GuidesIdRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesIdRoute: GuidesIdRoute,
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface ItinerariesRouteChildren {
  ItinerariesSlugRoute: typeof ItinerariesSlugRoute
}

const ItinerariesRouteChildren: ItinerariesRouteChildren = {
  ItinerariesSlugRoute: ItinerariesSlugRoute,
}

const ItinerariesRouteWithChildren = ItinerariesRoute._addFileChildren(
  ItinerariesRouteChildren,
)

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface PlanYourTripRouteChildren {
  PlanYourTripGuideRoute: typeof PlanYourTripGuideRoute
}

const PlanYourTripRouteChildren: PlanYourTripRouteChildren = {
  PlanYourTripGuideRoute: PlanYourTripGuideRoute,
}

const PlanYourTripRouteWithChildren = PlanYourTripRoute._addFileChildren(
  PlanYourTripRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AttractionsRoute: AttractionsRouteWithChildren,
  BookRoute: BookRouteWithChildren,
  ContactRoute: ContactRoute,
  CultureRoute: CultureRoute,
  GalleryRoute: GalleryRouteWithChildren,
  GuidesRoute: GuidesRouteWithChildren,
  HealthRoute: HealthRoute,
  ItinerariesRoute: ItinerariesRouteWithChildren,
  MapRoute: MapRoute,
  NewsRoute: NewsRouteWithChildren,
  PlanTripRoute: PlanTripRoute,
  PlanYourTripRoute: PlanYourTripRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EventsStatusRoute: EventsStatusRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  EventsTicketTokenRoute: EventsTicketTokenRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
