/** Common visitor countries for the booking form */
export const BOOKING_COUNTRIES = [
  "Ethiopia",
  "United States",
  "United Kingdom",
  "France",
  "Germany",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Sweden",
  "Norway",
  "Denmark",
  "Ireland",
  "Canada",
  "Australia",
  "Japan",
  "China",
  "South Korea",
  "India",
  "United Arab Emirates",
  "Saudi Arabia",
  "Kenya",
  "South Africa",
  "Nigeria",
  "Brazil",
  "Argentina",
  "Mexico",
  "Other",
] as const;
